module:
  code: MetadataTutorial
  presentation: "3"
content:
  - source: content/_build/html
    target: .tutorial
    overwrite: always
  - source: notebooks
    target: ""
    overwrite: if-unchanged
packages:
  pip:
    - polymatheia>=0.3.1
    - scipy
    - seaborn
packs:
  - name: jupyterlab
    options:
      version: 4
web_apps:
  - path: content
    command: python -m http.server -b 127.0.0.1 -d .tutorial {port}
    timeout: 60
    launcher_entry:
      title: Tutorial Content
server:
  default_path: /lab
