name: Deployment

on:
  push:
    branches: [default]

jobs:
  build_and_deploy:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Setup Environment
        run: |
          echo "PATH=$HOME/.local/bin:$PATH" >> $GITHUB_ENV
          echo "PIPX_HOME=$HOME/.local/pipx" >> $GITHUB_ENV
          echo "PIPX_BIN_DIR=$HOME/.local/bin" >> $GITHUB_ENV

      - name: Install Base Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install python3-venv pipx
          pipx install poetry
          pipx install ou-container-builder

      - name: Install Dependencies
        run: |
          poetry install --no-dev

      - name: Build the Tutorial
        run: |
          poetry run jb build --builder pdfhtml content
          cp content/_build/pdf/book.pdf content/metadatatutorial.pdf
          poetry run jb build content

      - name: Generate the Dockerfile
        run: |
          ou-container-builder --no-build

      - name: Build and push the Docker image
        uses: docker/build-push-action@v1.1.0
        with:
          username: scmmmh
          password: ${{ secrets.DOCKERACCESSTOKEN }}
          repository: scmmmh/metadatatutorial
          tags: latest
          tag_with_sha: true
          dockerfile: Dockerfile
